using EasyMoney.Api.Domain;

namespace EasyMoney.Api.Dtos;

// ============================================================
// Branch
// ============================================================

public record CreateBranchRequest(
    long TenantId,
    string? BranchCode,
    string BranchName,
    long BankId,
    string? RegistrationNo,
    DateOnly RegistrationDate,
    DateOnly BranchRegistrationDate,
    string Address,
    string? PhoneNumber,
    //string? Fax,
    string? Email,
    string? ReferenceNo,
    long? CashGlId,
    long? TransferGlId,
    long? AdjustmentGlId,
    DateOnly BiddingDate,
    DateOnly CutoffDate,
    DateOnly? BonusPaymentDate,
    BranchStatus Status,
    decimal MinimumRate,
    decimal MaximumRate,
    decimal Penalty,
    bool DoublePaymentAllowed,
    decimal MinimumIncrementAmount,
    decimal MinimumInstallmentAmount,
    decimal MaximumInstallmentAmount,
    string? OtherBank1,
    string? OtherBank2,
    DateOnly? PreviousDate,
    DateOnly? CurrentDate,
    DateOnly? NextDate
);

public record UpdateBranchRequest(
    string? BranchCode,
    string BranchName,
    long BankId,
    string? RegistrationNo,
    DateOnly RegistrationDate,
    DateOnly BranchRegistrationDate,
    string Address,
    string? PhoneNumber,
    //string? Fax,
    string? Email,
    string? ReferenceNo,
    long? CashGlId,
    long? TransferGlId,
    long? AdjustmentGlId,
    DateOnly BiddingDate,
    DateOnly CutoffDate,
    DateOnly? BonusPaymentDate,
    BranchStatus Status, 
    decimal MinimumRate,
    decimal MaximumRate,
    decimal Penalty,
    bool DoublePaymentAllowed,
    decimal MinimumIncrementAmount,
    decimal MinimumInstallmentAmount,
    decimal MaximumInstallmentAmount,
    string? OtherBank1,
    string? OtherBank2,
        DateOnly PreviousDate,
    DateOnly CurrentDate,
    DateOnly NextDate
);

public record BranchDto(
    long BranchId,
    long TenantId,
    string? BranchCode,
    string BranchName,
    long? BankId,
    string? RegistrationNo,
    DateOnly RegistrationDate,
    DateOnly BranchRegistrationDate,
    string? Address,
    string? PhoneNumber,
    //string? Fax,
    string? Email,
    string? ReferenceNo,
    long? CashGlId,
    long? AdjustmentGlId,
    long? TransferGlId,
    DateOnly? BiddingDate,
    DateOnly CutoffDate,
    DateOnly? BonusPaymentDate,
    BranchStatus Status,
    decimal MinimumRate,
    decimal MaximumRate,
    decimal Penalty,
    bool DoublePaymentAllowed,
    decimal MinimumIncrementAmount,
    decimal MinimumInstallmentAmount,
    decimal MaximumInstallmentAmount,
    string? OtherBank1,
    string? OtherBank2,
    DateTime CreatedAt,
    DateTime? modifiedAt,
    long? modifiedBy,
    DateOnly? PreviousDate,
    DateOnly? CurrentDate,
    DateOnly? NextDate

);
